#config.yml

imposters_path: "/"
port: 3000
host: ""
watcher: true
secure: false

cors:
  methods: ["GET"]
  headers: ["Content-Type"]
  exposed_headers: ["Cache-Control"]
  origins: ["*"]
  allow_credentials: true
