#config.yml

imposters_path: "/"
port: 3000
host: ""
# proxy:
#   url: http://apivivo.com
#   mode: missing
watcher: true
cors:
  methods: ["GET"]
  headers: ["Content-Type"]
  exposed_headers: ["Cache-Control"]
  origins: ["*"]
  allow_credentials: true
watcher: true
secure: true